export const NAV_LINKS = [
  { label: "Buy", href: "#" },
  { label: "Rent", href: "#" },
  { label: "Projects", href: "#" },
  { label: "Agents", href: "#" },
  { label: "Services", href: "#", hasDropdown: true },
];

export const POPULAR_SEARCHES = [
  "2 BHK in Mumbai",
  "3 BHK in Pune",
  "Villas in Bangalore",
  "Commercial in Delhi",
];

export const CATEGORY_CARDS = [
  {
    id: "card-1",
    title: "Luxury Apartments",
    location: "In Mumbai",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=85",
    initialTransform: {
      rotateY: -14,
      rotateX: 2,
      rotateZ: -3,
      scale: 1,
    },
  },
  {
    id: "card-2",
    title: "Independent Houses",
    location: "In Bangalore",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=85",
    initialTransform: {
      rotateY: 0,
      rotateX: 0,
      rotateZ: 0,
      scale: 1,
    },
  },
  {
    id: "card-3",
    title: "Plots & Land",
    location: "In Pune",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=85",
    initialTransform: {
      rotateY: 14,
      rotateX: 2,
      rotateZ: 3,
      scale: 1,
    },
  },
];

export const OVERLAP_FEATURES = [
  {
    id: "feat-1",
    icon: "home",
    title: "Verified Listings",
    description: "100% authentic properties",
    color: "blue",
  },
  {
    id: "feat-2",
    icon: "shield",
    title: "Trusted Agents",
    description: "RERA approved professionals",
    color: "emerald",
  },
  {
    id: "feat-3",
    icon: "star",
    title: "Best Prices",
    description: "Compare & save more",
    color: "amber",
  },
  {
    id: "feat-4",
    icon: "map-pin",
    title: "Prime Locations",
    description: "Homes in top neighbourhoods",
    color: "purple",
  },
];

export const WHY_CHOOSE_BENEFITS = [
  {
    id: "why-1",
    icon: "shield-check",
    title: "Verified Listings",
    description: "100% genuine properties with verified ownership.",
    iconBg: "bg-blue-50 text-blue-600",
  },
  {
    id: "why-2",
    icon: "coins",
    title: "Best Price Deals",
    description: "Compare prices and get the best value for your money.",
    iconBg: "bg-emerald-50 text-emerald-600",
  },
  {
    id: "why-3",
    icon: "headset",
    title: "Expert Guidance",
    description: "Get assistance from RERA certified agents.",
    iconBg: "bg-amber-50 text-amber-600",
  },
  {
    id: "why-4",
    icon: "file-text",
    title: "Hassle-Free Process",
    description: "From site visits to paperwork, we handle it all.",
    iconBg: "bg-purple-50 text-purple-600",
  },
];

export const PROPERTY_TYPES = [
  {
    id: "type-1",
    title: "Apartments",
    description: "Modern living spaces",
    listings: "12,500+ Listings",
    icon: "building-2",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: "type-2",
    title: "Villas",
    description: "Luxury and comfort",
    listings: "3,200+ Listings",
    icon: "home",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: "type-3",
    title: "Independent Houses",
    description: "Your own space",
    listings: "4,800+ Listings",
    icon: "house",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: "type-4",
    title: "Plots & Land",
    description: "Build your future",
    listings: "6,300+ Listings",
    icon: "map-pin",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: "type-5",
    title: "Commercial",
    description: "For your business",
    listings: "2,900+ Listings",
    icon: "briefcase",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=85",
  },
  {
    id: "type-6",
    title: "Rental Properties",
    description: "Flexible living options",
    listings: "8,400+ Listings",
    icon: "key",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=85",
  },
];

export const TRUST_STATS = [
  {
    id: "stat-1",
    value: "1M+",
    number: 1000000,
    prefix: "",
    suffix: "M+",
    displayNum: "1M+",
    label: "Happy Home Seekers",
    icon: "home",
  },
  {
    id: "stat-2",
    value: "50,000+",
    number: 50000,
    prefix: "",
    suffix: "+",
    displayNum: "50,000+",
    label: "Verified Properties",
    icon: "check-circle",
  },
  {
    id: "stat-3",
    value: "5,000+",
    number: 5000,
    prefix: "",
    suffix: "+",
    displayNum: "5,000+",
    label: "Trusted Agents",
    icon: "users",
  },
  {
    id: "stat-4",
    value: "4.8/5",
    number: 4.8,
    prefix: "",
    suffix: "/5",
    displayNum: "4.8/5",
    label: "Customer Rating",
    icon: "trophy",
  },
];

export const LATEST_PROPERTIES = [
  {
    id: "prop-1",
    price: "₹ 1.25 Cr",
    type: "2 BHK Apartment",
    location: "Thane West, Mumbai",
    area: "1200 sq.ft",
    beds: 2,
    baths: 2,
    tag: "Featured",
    tagColor: "bg-[#6366f1] text-white",
    image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "prop-2",
    price: "₹ 3.2 Cr",
    type: "4 BHK Villa",
    location: "Whitefield, Bangalore",
    area: "2400 sq.ft",
    beds: 4,
    baths: 4,
    tag: "New",
    tagColor: "bg-[#10b981] text-white",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "prop-3",
    price: "₹ 85 Lakh",
    type: "3 BHK Apartment",
    location: "Wakad, Pune",
    area: "1450 sq.ft",
    beds: 3,
    baths: 3,
    tag: "Ready to Move",
    tagColor: "bg-[#059669] text-white",
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "prop-4",
    price: "₹ 2.1 Cr",
    type: "3 BHK Apartment",
    location: "Sector 62, Gurgaon",
    area: "1800 sq.ft",
    beds: 3,
    baths: 3,
    tag: "High Rental Yield",
    tagColor: "bg-[#2563eb] text-white",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "prop-5",
    price: "₹ 4.5 Cr",
    type: "5 BHK Penthouse",
    location: "Bandra West, Mumbai",
    area: "3500 sq.ft",
    beds: 5,
    baths: 5,
    tag: "Exclusive",
    tagColor: "bg-[#8b5cf6] text-white",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "prop-6",
    price: "₹ 1.8 Cr",
    type: "3 BHK Luxury Villa",
    location: "Koramangala, Bangalore",
    area: "2100 sq.ft",
    beds: 3,
    baths: 3,
    tag: "Trending",
    tagColor: "bg-[#ea580c] text-white",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=900&q=85",
  },
];
